version: '3'

services:
  vscode-server:
    image: yassinsiouda/vscode-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vscode-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - PASSWORD=password  # Set your password here
      - SUDO_PASSWORD=password  # For sudo privileges
    volumes:
      - ./config:/config
      - ./workspace:/config/workspace
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket for Docker in Docker
    ports:
      - "8443:8443"
    restart: unless-stopped
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]